title: "Daniel Robert Buccat | 7OOP Portfolio"
description: "A showcase of Midterm and Final OOP Projects â€” City College of Angeles"
theme: jekyll-theme-minimal
show_downloads: false
markdown: kramdown

logo: "Images/Profile.jpg"
github:
  is_project_page: false

sass:
  sass_dir: Assets/CSS
  style: compressed

include:
  - Assets

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
