title: "Daniel Robert Buccat | 7OOP Portfolio"
description: "1st Semester 7OOP Projects"
theme: jekyll-theme-minimal
show_downloads: false
markdown: kramdown

logo: "Images/Profile.jpg"
github:
  is_project_page: false

color:
  background: "#0a0a0a"
  text: "#f5f5f5"
  accent: "#00f0ff"

nav:
  - name: "ğŸ  Home"
    link: "/"
  - name: "ğŸ“˜ Midterms"
    link: "/Projects/Midterms/"
  - name: "ğŸ“ Finals"
    link: "/Projects/Finals/"
  - name: "ğŸ“« Contact"
    link: "#contact"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

social_links:
  - name: "Facebook"
    url: "https://www.facebook.com/danielrobbuccat"
  - name: "Instagram"
    url: "https://www.instagram.com/danielrobbuccat/"
  - name: "YouTube"
    url: "https://www.youtube.com/@DanielRobertBuccat"
  - name: "TikTok"
    url: "https://www.tiktok.com/@danielrobertbuccat"
    
sass:
  style: compressed

google_analytics: false
future: true
highlighter: rouge
